-- vim.o.foldcolumn = '0' -- '0' is not bad
-- vim.o.foldlevel = 1 -- Using ufo provider need a large value, feel free to decrease the value
-- vim.o.foldlevelstart = 1
-- vim.o.foldenable = true
--
-- require('ufo').setup({
--     provider_selector = function(bufnr, filetype, buftype)
--         return {'treesitter', 'indent'}
--     end
-- })
--
-- vim.keymap.set('n', '<leader>s', require('ufo').openFoldsExceptKinds)
-- vim.keymap.set('n', '<leader>d', require('ufo').closeFoldsWith)
-- vim.keymap.set('n', '<A-v>', require('ufo').peekFoldedLinesUnderCursor)
-- vim.keymap.set('n', 'K', function()
--     local winid = require('ufo').peekFoldedLinesUnderCursor()
--     if not winid then
--         -- choose one of coc.nvim and nvim lsp
--         -- vim.fn.CocActionAsync('definitionHover') -- coc.nvim
--         vim.lsp.buf.hover()
--     end
-- end)
